# Generated by Django 3.2.8 on 2021-10-28 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('lures', 'lures'), ('fishing reel', 'fishing reel'), ('accessories', 'accessories'), ('spinning', 'spinning')], max_length=30, verbose_name='Категории'),
        ),
    ]
