# Generated by Django 3.2.8 on 2021-10-28 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_product_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('lures', 'lures'), ('accessories', 'accessories'), ('spinning', 'spinning'), ('fishing reel', 'fishing reel')], max_length=30, verbose_name='Категории'),
        ),
        migrations.AlterIndexTogether(
            name='product',
            index_together={('id',)},
        ),
    ]
