# Generated by Django 3.2.8 on 2021-10-28 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20211028_1257'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('accessories', 'accessories'), ('lures', 'lures'), ('spinning', 'spinning'), ('fishing reel', 'fishing reel')], max_length=30, verbose_name='Категории'),
        ),
        migrations.AlterIndexTogether(
            name='product',
            index_together=set(),
        ),
    ]
