# Generated by Django 3.2.8 on 2021-11-01 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20211028_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='specifications',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('lures', 'lures'), ('spinning', 'spinning'), ('accessories', 'accessories'), ('fishing reel', 'fishing reel')], max_length=30, verbose_name='Категории'),
        ),
    ]
