# Generated by Django 3.2.8 on 2021-11-08 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20211101_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('spinning', 'spinning'), ('accessories', 'accessories'), ('lures', 'lures'), ('fishing reel', 'fishing reel')], max_length=30, verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='product',
            name='specifications',
            field=models.TextField(null=True, verbose_name='Характеристики'),
        ),
    ]
